language: php

php:
  # - 5.4
  # - 5.5
  # - 5.6
  # - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - export PATH=/home/travis/.config/composer/vendor/bin:$PATH
  - git fetch --unshallow --tags
  # - composer install --prefer-source
  - composer global require 'kherge/box=~2.4' --prefer-source
  # - wget https://scrutinizer-ci.com/ocular.phar

script:
  # - php vendor/atoum/atoum/scripts/coverage.php --format xml --output clover.xml
  - composer install --no-dev --optimize-autoloader
  - composer build
  # - composer install
  # - PICKLE_BEHAT_PROCESS_TIMEOUT=0 vendor/bin/behat --format=progress

after_script:
  # - php ocular.phar code-coverage:upload --format=php-clover clover.xml
  - chmod +x ./pickle.phar
  - ls -lah pickle.phar
  - ls -lah $(php-config --extension-dir)
  - ./pickle.phar install mongodb --defaults -n -vvv
  - ls -lah $(php-config --extension-dir)

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: pickle.phar
  skip_cleanup: true
  on:
    tags: true
    php: 7.3
