version: ~> 1.0

language: php

php:
  # - 5.4
  # - 5.5
  # - 5.6
  # - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - export PATH=/home/travis/.config/composer/vendor/bin:$PATH
  - git fetch --unshallow --tags
  # - composer install --prefer-source
  - composer global require 'kherge/box=~2.4' --prefer-source
  # - wget https://scrutinizer-ci.com/ocular.phar

script:
  - git tag nightly -f
  # - php vendor/atoum/atoum/scripts/coverage.php --format xml --output clover.xml
  - composer install --no-dev --optimize-autoloader || composer install --no-dev --optimize-autoloader --ignore-platform-reqs
  - composer build
  - mv pickle.phar pickle.phar.back
  # - composer install
  # - PICKLE_BEHAT_PROCESS_TIMEOUT=0 vendor/bin/behat --format=progress
  - composer require nunomaduro/collision --update-no-dev || true
  - composer build || true
  - cp -a pickle.phar pickle-debug.phar || true
  - cp -a pickle.phar.back pickle.phar || true
  - ls -lah

after_script:
  # - php ocular.phar code-coverage:upload --format=php-clover clover.xml
  - chmod +x ./pickle.phar
  - ls -lah $(php-config --extension-dir)
  - php -m > 1
  - ./pickle.phar install mongodb --defaults -n -vvv
  - ./pickle.phar install yaml --defaults -n -vvv --defaults --cleanup --strip
  - ls -lah $(php-config --extension-dir)
  - php -m > 2
  - diff 1 2

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: 
    - pickle.phar
    - pickle-debug.phar
    skip_cleanup: true
    on:
      tags: true
      php: 7.3
      repo: khs1994-php/pickle
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: 
    - pickle.phar
    - pickle-debug.phar
    skip_cleanup: true
    on:
      tags: false
      php: 7.3
      repo: khs1994-php/pickle
    overwrite: true
